# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Multipass
email: webteam@canonical.com
description: > # this means to ignore newlines until "baseurl:"
  It's a system that orchestrates the creation, management and maintenance of
  virtual machines and associated Ubuntu images to simplify development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://multipass.io" # the base hostname & protocol for your site
exclude: [
  'LICENCE',
  'LICENSE',
  'README.md',
  'gulpfile.babel.js',
  'package.json',
  'vendor/bundle',
  'Dockerfile',
  'Gemfile*',
  'nginx.conf',
  'node_modules',
  'run',
  'yarn.lock'
]

# Build settings
markdown: kramdown

# only build incrementally
incremental: true
