title: Multipass
email: webteam@canonical.com
description: > 
  It's a system that orchestrates the creation, management and maintenance of
  virtual machines and associated Ubuntu images to simplify development.
url: "https://multipass.run"
exclude: [
  'LICENCE',
  'LICENSE',
  'README.md',
  'gulpfile.babel.js',
  'package.json',
  'vendor/bundle',
  'Dockerfile',
  'Gemfile*',
  'nginx.conf',
  'node_modules',
  'run',
  'yarn.lock'
]
incremental: true
include: ["_status"]

